print('Cau A')
a = int(input('Nhap  so thu 1: '))
b = int(input('Nhap  so thu 2: '))
print('Tong:')
print('Cach 1: {} + {} = {}'.format(a, b, a+b))
print('Cach 2:', a, '+', b, '=', a+b)
print('Cach 3: %d + %d = %d' %(a, b, a+b))
print(f'Cach 4: {a} + {b} = {a+b}')

print('\nCau B')
a, b = input('Nhap 2 so cach nhau boi dau phay: ').split(',')
a = int(a)
b = int(b)
print(f'Tong: {a} + {b} = {a+b}')
